services:
  n8n:
    image: n8nio/n8n
    container_name : n8n
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_HOST=n8n.softsystem.dev
      - N8N_PROTOCOL=https
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgresql
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=password
    restart: always

    volumes:
      - data:/home/node/.n8n
      - files:/files

volumes:
  data:
  files:

networks:
  default:
    external: true
    name: base
